---
abstract: tokenize indented lines in text
author:
  - 'Michael Roberts <michael@vivtek.com>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Tokenize-Indented
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/Vivtek/Text-Tokenize-Indented.git
version: 0.01
